import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import "@mantine/notifications/styles.css";
import { nordTheme } from "./theme";
import { AdminLayout } from "@/components/layout/AdminLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={nordTheme}>
          <Notifications />
          <AdminLayout>
            <div>{children}</div>
          </AdminLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
